apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon
  namespace: hackathon-pos-tech
  labels:
    app: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: hackathon
          image: gleniomontovani/hackathon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:            
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo-root-username
                  name: hackathon-secret
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-root-password      
                  name: hackathon-secret
            - name: AWS_ACCESS_KEY
              value: ${AWS_ACCESS_KEY_ID}    
            - name: AWS_SECRET_ACCESS
              value: ${AWS_SECRET_ACCESS_KEY}
            - name: REGION_AWS
              value: ${AWS_REGION}               
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
                        