apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hackathon-hpa
  namespace: hackathon-pos-tech
  labels:
    app: hackathon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hackathon
  minReplicas: 1 # ajuste conforme necessário
  maxReplicas: 1 # ajuste conforme necessário
  targetCPUUtilizationPercentage: 80 # ajuste conforme necessário
