apiVersion: v1
data:
  postgresql-username: cG9zdGdyZXM=
  postgresql-password: cG9zdGdyZXNxbA==
  mongo-root-username: Z2xlbmlvbW9udG92YW5p
  mongo-root-password: OElneklwWHNhYVJtSUN1cA==
kind: Secret
metadata:
  name: hackathon-secret
  namespace: hackathon-pos-tech
  labels:
    app: hackathon