apiVersion: v1
kind: Service
metadata:
  name: hackathon-service
  namespace: hackathon-pos-tech
  labels:
    app: hackathon
spec:
  selector:
    app: hackathon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
